# Generated by Django 3.1.2 on 2020-11-15 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Viajes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aeropuesto',
            new_name='Aeropuerto',
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracionV', models.FloatField(verbose_name='Tiempo')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Arribos', to='Viajes.aeropuerto')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Salidas', to='Viajes.aeropuerto')),
            ],
        ),
    ]
